export const AppActionsTypes ={
    FETCH_DATA_LOADING:"FETCH_DATA_LOADING",
    FETCH_DATA_SUCCESS:"FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE:"FETCH_DATA_FAILURE",
    ADD_DATA_SUCCESS:"ADD_DATA_SUCCESS",
    ADD_DATA_FAILURE:"ADD_DATA_FAILURE"
}